### ISSUE TITLE
All pages result in 500 server error on production server

### ISSUE THREAD

**Issue by stevenlavine** [isaachinman/next-i18next#1080]
I'm building a Next,js react site using next-i18next version 8.1.2 and have added the translation config and the site works correctly without any issues. However when I deploy the code to Vercel the homepage renders fine, but clicking a link or going directly to a page results in a 500 server error.

I have run next build && next start locally and the website works correctly. Is this an issue with the code or Vercel?

**Comment by isaachinman** [comment]
You'll need to paste the error output from your function logs in Vercel.

**Comment by stevenlavine** [comment]
I have worked it out. Vercel has a serverless environment so it appears that next-i18next does not run correctly. I have moved the site over to a node.js server proxied by Nginx and all is working correctly.

**Comment by isaachinman** [comment]
Hey @stevenlavine – respectfully, I don't think you have worked it out. The [demo](https://next-i18next.com/) within this repo is hosted on Vercel, as are many other `next-i18next` projects.

**Comment by stevenlavine** [comment]
Hmm OK. I stand corrected :)

**Comment by isaachinman** [comment]
As in, there should not be an issue. If you feel as though you've found a bug, please post the error output from your Vercel logs.

**Comment by stevenlavine** [comment]
My mind must have been asleep. Looking at the logs I get this error

```
2021-03-19T16:00:44.676Z	b095ac33-5a43-49f1-a515-2c6e3ffceee3	ERROR	Error: ENOENT: no such file or directory, scandir '/var/task/public/locales/en'
    at Object.readdirSync (fs.js:955:3)
    at getAllNamespaces (/var/task/node_modules/next-i18next/dist/commonjs/config/createConfig.js:113:21)
    at createConfig (/var/task/node_modules/next-i18next/dist/commonjs/config/createConfig.js:118:29)
    at _callee$ (/var/task/node_modules/next-i18next/dist/commonjs/serverSideTranslations.js:105:53)
    at tryCatch (/var/task/node_modules/regenerator-runtime/runtime.js:63:40)
    at Generator.invoke [as _invoke] (/var/task/node_modules/regenerator-runtime/runtime.js:293:22)
    at Generator.next (/var/task/node_modules/regenerator-runtime/runtime.js:118:21)
    at asyncGeneratorStep (/var/task/node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:24)
    at _next (/var/task/node_modules/@babel/runtime/helpers/asyncToGenerator.js:25:9)
    at processTicksAndRejections (internal/process/task_queues.js:97:5) {
  errno: -2,
  syscall: 'scandir',
  path: '/var/task/public/locales/en'
}
RequestId: b095ac33-5a43-49f1-a515-2c6e3ffceee3 Error: Runtime exited with error: exit status 1
Runtime.ExitError
```

**Comment by stevenlavine** [comment]
Further to my last comment, If I go to the URI /locales/en/common.js the file is found

**Comment by isaachinman** [comment]
Please search previous issues as this has been discussed a number of times. [This comment](https://github.com/isaachinman/next-i18next/issues/1005#issuecomment-791932403) may help you. Good luck!

**Comment by stevenlavine** [comment]
I did not even notice that thread. Many thanks, that solved my issue. I hate Fridays :D
