### ISSUE TITLE
Vercel/getServerSideProps: no such file or directory

### ISSUE THREAD

**Issue by chr-ge** [isaachinman/next-i18next#1198]
## Describe the bug
When using `getServerSideProps` with `serverSideTranslations` on Vercel, I am getting the following error:
```
Error: ENOENT: no such file or directory, scandir '/var/task/public/locales/en-US'
    at Object.readdirSync (fs.js:1021:3)
    at getAllNamespaces (/var/task/node_modules/next-i18next/dist/commonjs/config/createConfig.js:129:21)
    at createConfig (/var/task/node_modules/next-i18next/dist/commonjs/config/createConfig.js:134:29)
    at _callee$ (/var/task/node_modules/next-i18next/dist/commonjs/serverSideTranslations.js:117:53)
    at tryCatch (/var/task/node_modules/regenerator-runtime/runtime.js:63:40)
    at Generator.invoke [as _invoke] (/var/task/node_modules/regenerator-runtime/runtime.js:293:22)
    at Generator.next (/var/task/node_modules/regenerator-runtime/runtime.js:118:21)
    at asyncGeneratorStep (/var/task/node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:24)
    at _next (/var/task/node_modules/@babel/runtime/helpers/asyncToGenerator.js:25:9)
    at processTicksAndRejections (internal/process/task_queues.js:93:5) {
  errno: -2,
  syscall: 'scandir',
  path: '/var/task/public/locales/en-US'
}
```

Weirdly, on localhost it works fine.
Here is my code:
```tsx
export const getServerSideProps: GetServerSideProps = async (ctx) => {
  const token = ctx.params?.token
  const invite = await fetch(...)

  if ([403, 404].includes(invite.status)) {
    return {
      notFound: true,
    }
  }

  return {
    props: {
      ...(await serverSideTranslations(ctx.locale!, ['common'])),
      token
    },
  }
}
```

## Occurs in next-i18next version
8.2.0

## Steps to reproduce
You must provide a reproducible repository, or copy/paste blocks of code which are sufficient to reproduce the bug.

## Expected behaviour
Not have an error and render the page with 200 status.

## Additional context
I am using Typescript.

next-i18next.config.js:
```js
module.exports = {
  i18n: {
    locales: ['en-US', 'fr'],
    defaultLocale: 'en-US',
    fallbackLng: 'en-US'
  },
}

```

**Comment by isaachinman** [comment]
There have been numerous issues about this. You need to use `path.resolve` to get Vercel to include the translation files in your serverless deployment. Good luck!

**Comment by chr-ge** [comment]
Ok thank you
