### ISSUE TITLE
Initial locale argument was not passed into serverSideTranslations when using next-compose-plugins

### ISSUE THREAD

**Issue by ziedHamdi** [isaachinman/next-i18next#1379]
## Describe the bug
I started having the issue since I added next-compose-plugins to be able to run bundle-analyzer along with i18next

next.config.js
```
const withPlugins = require('next-compose-plugins')
const { i18n } = require('./next-i18next.config');
const withBundleAnalyzer = require("@next/bundle-analyzer")({
    enabled: process.env.ANALYZE === "true",
});

module.exports = withPlugins([
    [withBundleAnalyzer],
    i18n
])

```

Things were working fine with this config:
```
const { i18n } = require('./next-i18next.config');

module.exports = {
    i18n,
};
```

Now I'm stuck for an hour trying to figure out what started to be missing to i18next. 
I think this is a topic worth considering by the i18next team since it is something everyone will encounter when he will want to optimize his app

This is the error I get:

```
Error occurred prerendering page "/". Read more: https://nextjs.org/docs/messages/prerender-error
Error: Initial locale argument was not passed into serverSideTranslations
    at _callee$ (D:\Work\WeAlly.org\node_modules\next-i18next\dist\commonjs\serverSideTranslations.js:169:19)
    at tryCatch (D:\Work\WeAlly.org\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (D:\Work\WeAlly.org\node_modules\regenerator-runtime\runtime.js:293:22)

```

## Occurs in next-i18next version
```
    "next-compose-plugins": "^2.2.1",
    "next-i18next": "^8.5.1",

```

## Screenshots
![image](https://user-images.githubusercontent.com/7271508/130938128-a12419f0-8d9a-47f3-91a1-23699a0750be.png)

## OS (please complete the following information)
 - Device: Win 10
 - "next": "^11.0.1",

**Comment by isaachinman** [comment]
Please provide a reproducible repository.

**Comment by sweetmilkys** [comment]
I think you should change next.config.js like this.

```
const withPlugins = require('next-compose-plugins')
const { i18n } = require('./next-i18next.config');
const withBundleAnalyzer = require("@next/bundle-analyzer")({
    enabled: process.env.ANALYZE === "true",
});

module.exports = withPlugins([withBundleAnalyzer], { i18n });
```

or 

```
const withPlugins = require('next-compose-plugins')
const { i18n } = require('./next-i18next.config');
const withBundleAnalyzer = require("@next/bundle-analyzer")({
    enabled: process.env.ANALYZE === "true",
});
const plugins = [withBundleAnalyzer];
const nextConfig = { i18n };

module.exports = withPlugins(plugins, nextConfig);
```

see the [usage](https://www.npmjs.com/package/next-compose-plugins#usage)
