### ISSUE TITLE
Can not use serverSideTranslations on Vercel

### ISSUE THREAD

**Issue by rynrn** [isaachinman/next-i18next#1475]
## Describe the bug
In my index page i'm using `serverSideTranslations` function. getting error about finding file of translation.
this error happens only on pages that used by `serverSideTranslations`.

I deployed to Vercel and Netlify. in both of them i'v got the same error.

in `_app.js` i'm using `appWithTranslation`.

Dependencies:
```javascript
"dependencies": {
    "@fortawesome/fontawesome-free": "^5.15.4",
    "@netlify/plugin-nextjs": "^3.9.2",
    "axios": "^0.21.1",
    "bootstrap": "^4.6.0",
    "dayjs": "^1.10.4",
    "dotenv": "^8.2.0",
    "fs-extra": "^10.0.0",
    "is-mobile": "^3.0.0",
    "next": "^11.1.2",
    "next-i18next": "^8.9.0",
    "next-seo": "^4.20.0",
    "node-fetch": "^2.6.1",
    "parse": "^3.1.0",
    "react": "17.0.1",
    "react-bootstrap": "^1.5.0",
    "react-dom": "17.0.1",
    "react-infinite-scroller": "^1.2.4",
    "recoil": "^0.1.2",
    "sass": "^1.43.2",
    "ts-node": "^9.1.1"
  }
```

next.config.js
```javascript
const path = require('path');
const { PHASE_DEVELOPMENT_SERVER } = require('next/constants')
const i18NextConfig = require('./next-i18next.config');

const prodConfig = {
    generateBuildId: () => 'build-id',
    compress: true,
    target: 'serverless',
    i18n: i18NextConfig.i18n,
    sassOptions: {
        includePaths: [path.join(__dirname, 'styles')],
    },
}
module.exports = (phase, { defaultConfig }) => {
    if (phase === PHASE_DEVELOPMENT_SERVER) {
        return {
            ...defaultConfig,
            ...prodConfig,
            compress: false,
        }
    }

    return prodConfig;
}

```

next-i18next.config.js
```javascript
const path = require('path');

module.exports = {
  i18n: {
    defaultLocale: 'he',
    locales: ['he'],
    localePath: path.resolve('./locales'), // <<< i tried to put this line here
  },
  keySeparator: '>',
  nsSeparator: '|',
  reloadOnPrerender: false,
  localePath: path.resolve('./locales'), // <<< and also here
};
```

## Error message from Vercel lambda function

ng request: Error: ENOENT: no such file or directory, scandir '/var/task/public/locales/he'
    at Object.readdirSync (fs.js:1043:3)
    at getLocaleNamespaces (/var/task/node_modules/next-i18next/dist/commonjs/config/createConfig.js:175:23)
    at /var/task/node_modules/next-i18next/dist/commonjs/config/createConfig.js:181:20
    at Array.map (<anonymous>)
    at getNamespaces (/var/task/node_modules/next-i18next/dist/commonjs/config/createConfig.js:180:44)
    at createConfig (/var/task/node_modules/next-i18next/dist/commonjs/config/createConfig.js:221:29)
    at _callee$ (/var/task/node_modules/next-i18next/dist/commonjs/serverSideTranslations.js:199:53)
    at tryCatch (/var/task/node_modules/regenerator-runtime/runtime.js:63:40)
    at Generator.invoke [as _invoke] (/var/task/node_modules/regenerator-runtime/runtime.js:294:22)
    at Generator.next (/var/task/node_modules/regenerator-runtime/runtime.js:119:21) {
  errno: -2,
  syscall: 'scandir',
  path: '/var/task/public/locales/he'
}

**Comment by gendronb** [comment]
I really appreciate all the efforts and work you are putting into this, @isaachinman, but @rynrn **did** use `path.resolve`. And still have this issue...

@rynrn did you find a solution?

I know it may not directly related to `next-i18next` (and more to the way the Vercel filesystem is organized), but since `next-i18nex`t is built specifically for `NextJs`, and since probably 99% of `NextJs `deployments are on Vercel, it may be fair to say that it is a problem `next-i18next` should address...

I'm also having this problem when using `getStaticPaths` with dynamic paths that are not known at build time. For known paths, everything's OK.

For example, given the following :

```
// inside /pages/[id].js
export async function getStaticPaths() {

  const paths = [
    { params: { id: 1 } }
  ]
  
  return {
    paths,
    fallback: true
  }
}
```

`/pages/1` will be created at build time, and will work, but `/pages/2` will be built dynamically, and will fail (log below)...

```
2021-11-04T19:08:57.752Z	39913010-96e6-4074-92f5-326f8f6f71e2	DEBUG	/var/task/apps/collect/public/locales
2021-11-04T19:08:59.281Z	39913010-96e6-4074-92f5-326f8f6f71e2	ERROR	Error: ENOENT: no such file or directory, scandir '/var/task/apps/collect/public/locales/fr'
    at Object.readdirSync (fs.js:1043:3)
    at getLocaleNamespaces (/var/task/node_modules/next-i18next/dist/commonjs/config/createConfig.js:175:23)
    at /var/task/node_modules/next-i18next/dist/commonjs/config/createConfig.js:181:20
    at Array.map (<anonymous>)
    at getNamespaces (/var/task/node_modules/next-i18next/dist/commonjs/config/createConfig.js:180:44)
    at createConfig (/var/task/node_modules/next-i18next/dist/commonjs/config/createConfig.js:221:29)
    at _callee$ (/var/task/node_modules/next-i18next/dist/commonjs/serverSideTranslations.js:199:53)
    at tryCatch (/var/task/node_modules/next-i18next/node_modules/regenerator-runtime/runtime.js:63:40)
    at Generator.invoke [as _invoke] (/var/task/node_modules/next-i18next/node_modules/regenerator-runtime/runtime.js:294:22)
    at Generator.next (/var/task/node_modules/next-i18next/node_modules/regenerator-runtime/runtime.js:119:21) {
  errno: -2,
  syscall: 'scandir',
  path: '/var/task/apps/collect/public/locales/fr'
}
RequestId: 39913010-96e6-4074-92f5-326f8f6f71e2 Error: Runtime exited with error: exit status 1
Runtime.ExitError
```

My use case prevents me from genereating a list of paths in advance (as they are created dynamically by the users), so I really need to find a solution...

**Comment by isaachinman** [comment]
@gendronb Can you provide a reproducible repo?

**Comment by gendronb** [comment]
@isaachinman

Again, I appreciate your efforts, and I don't want to waste your time, so I did some additionnal experiments.

I must mention that my own  project is not a "normal" `NextJs` project, as it a monorepo scaffolded using [`Nx` ](https://nx.dev/). As such, the `next-i18next.config.js` is not at the project root, but 2 levels up (inside `/apps/my-app`).

Originally, my `next-i18next.config.js` is like below:

```
const path = require('path')

module.exports = {
  i18n: {
    locales: ['en', 'fr'],
    defaultLocale: 'fr'
  },
  localeDetection: false,
  debug: true,
  localePath: path.resolve('./apps/my-app/public/locales'),
  react: { useSuspense: false }
}
```

This configuration works perfectly locally, but dynamic page generation fails on Vercel (as per my previous message).

I tried chanching the localePath to `localePath: path.resolve('./apps/my-app/public/locales')`, but then the build process itself fails (for static pages, like `404`).

I did create a reproducible repo for you, but since it is a "normal" `NextJs `project, the problem do not occur. In order to really reproduce my issue, I will have to scaffold a project with `Nx`.

**Comment by isaachinman** [comment]
@gendronb I think you'd be better off opening an issue on the [vercel](https://github.com/vercel/vercel) repo, with that minimal `Nx` repository to help them reproduce.

Feel free to also post it here. I can take a look, but cannot offer any promises in regards to the Vercel platform itself.

**Comment by gendronb** [comment]
@isaachinman thanks, will do and keep you informed.

In the meantime, any idea about how I could load and inject the translations server-side, maybe with a normal `require` or `import` statement?

**Comment by isaachinman** [comment]
As I said, I would need to see your reproducible repo to give any advice.
