### ISSUE TITLE
Unable to use next-i18next with Next.js v12

### ISSUE THREAD

**Issue by TeosVerdi** [isaachinman/next-i18next#1515]
## Describe the bug
When i try to boot up project with next v12.0.3, i get the following error:
```
Error: Default namespace not found at public\locales\undefined\common.json
    at createConfig (C:\<path>\node_modules\next-i18next\dist\commonjs\config\createConfig.js:154:17)
    at _callee$ (C:\<path>\node_modules\next-i18next\dist\commonjs\serverSideTranslations.js:199:53)
    at tryCatch (C:\<path>\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\<path>\node_modules\regenerator-runtime\runtime.js:294:22)
    at Generator.next (C:\<path>\node_modules\regenerator-runtime\runtime.js:119:21)
    at asyncGeneratorStep (C:\<path>\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\<path>\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
```
The following error doesn't occur on nextjs v11.

## Occurs in next-i18next version
v8.10.0

## Steps to reproduce
I'm using the following settings:
`next-i18next.config.js`
```
module.exports = {
  i18n: {
    locales: ['ru', 'en'],
    defaultLocale: 'ru',
    localeDetection: false,
    reloadOnPrerender: true,
  },
};
```

`next.config.js`
```
const { i18n } = require('./next-i18next.config');
module.exports = {
    i18n,
    webpack(config) {
      ...
    },
    env: {...}
);
```

`pages/<any>.ts`

```
export const getServerSideProps: GetServerSideProps = async (context) => {
  return {
    props: {
      ...(await serverSideTranslations(String(context.locale), [
        'common',
      ])),
    },
  };
};
```

## Expected behaviour
The project builds and works as expected.

## OS (please complete the following information)
 - Device: Personal PC
 - Browser: Any

**Comment by TeosVerdi** [comment]
The issue was related to react-hook-form error.

**Comment by enesozturk** [comment]
Same here, also using `react-hook-form` too, but not in the page I got error. How did you solve that? @TeosVerdi
