### ISSUE TITLE
Cannot use getServerSideProps to fetch translations

### ISSUE THREAD

**Issue by vivianedias** [isaachinman/next-i18next#1536]
## Describe the bug
The issue first began when I used `serverSideTranslations` inside a dynamic route (that used getServerSideProps) in my NextJS project. Then, later found out that even if I used `serverSideTranslations` inside a static route using `getServerSideProps` I was having the same problems. 

Locally, everything is working fine. The problem is when I deploy the app to production. The page throws either a 404 or 500 error.

You can see how I'm using it on this [page](https://github.com/vivianedias/hacking-vigilance/blob/main/src/pages/quiz/index.jsx). 
And the website page that is throwing a 500 error is available [here](https://hacking-vigilance.vercel.app/quiz).

## Occurs in next-i18next version
^8.6.0 (I also tested using ^9.1.0 - same issue)

## Expected behaviour
The `getServerSideProps` func provided by NextJS should load the translations in the same way `getStaticProps` func does.

## Screenshots
<img width="500" alt="image" src="https://user-images.githubusercontent.com/9057801/142769422-5879774b-84c9-4641-ab50-aa03509e3ad5.png">

## OS (please complete the following information)
 - Device: Macbook pro 2019
 - Browser: Firefox 94.0.1

**Comment by isaachinman** [comment]
You will need to provide some sort of stacktrace.

**Comment by vivianedias** [comment]
> You will need to provide some sort of stacktrace.

From where?

**Comment by isaachinman** [comment]
From wherever the 500 is occurring.

**Comment by vivianedias-tw** [comment]
Stack trace:
`"Error: ENOENT: no such file or directory, scandir '/var/task/public/locales/pt-BR'\n    at Object.readdirSync (fs.js:1047:3)\n    at getLocaleNamespaces (/var/task/node_modules/next-i18next/dist/commonjs/config/createConfig.js:175:23)\n    at /var/task/node_modules/next-i18next/dist/commonjs/config/createConfig.js:181:20\n    at Array.map (<anonymous>)\n    at getNamespaces (/var/task/node_modules/next-i18next/dist/commonjs/config/createConfig.js:180:44)\n    at createConfig (/var/task/node_modules/next-i18next/dist/commonjs/config/createConfig.js:221:29)\n    at _callee$ (/var/task/node_modules/next-i18next/dist/commonjs/serverSideTranslations.js:199:53)\n    at tryCatch (/var/task/node_modules/regenerator-runtime/runtime.js:63:40)\n    at Generator.invoke [as _invoke] (/var/task/node_modules/regenerator-runtime/runtime.js:294:22)\n    at Generator.next (/var/task/node_modules/regenerator-runtime/runtime.js:119:21)"`

Error object:

```
{
  code: "ENOENT",
  errno: -2,
  path: "/var/task/public/locales/pt-BR",
  syscall: "scandir"
}
```

**Comment by isaachinman** [comment]
Are you deploying on Vercel?

**Comment by vivianedias-tw** [comment]
yes! @isaachinman

**Comment by CameronCT** [comment]
I am using server-side and static generation for my current app. And while I do use `path.resolve` it is actually very inconsistent on both Vercel and Netlify deployment (Netlify w/NextJS Plugin)

Using NextJS v12 as well if it helps.
```
module.exports = {
  i18n: {
    localeDetection: false,
    defaultLocale: 'en',
    locales: ["en", "fr-FR", "es-MX", "pt-BR","de-DE", "no", "hr", "nl", "it-IT", "ar", "el-GR", "zh-Hans-CN"],
    debug: process.env.NODE_ENV === 'development',
    defaultNS: `translation`,
    localePath: path.resolve('./public/locales')
  },
  react: { useSuspense: false } 
};
```

If I re-deploy on Netlify I can get it to work 1/10 chances for some reason, the NextJS Plugin is the v4 beta so there is likely a reason considering NextJS v12 introduces some breaking changes. However Vercel should still work fine, but maybe next-i18next has to do something separately for v12?
