### ISSUE TITLE
ReactIs.isMemo is not a function

### ISSUE THREAD

**Issue by hnq90** [isaachinman/next-i18next#203]
## Describe the bug
When I try to use `appWithTranslation` HOC with `_app.js`, I got following error:

```
Note that pages will be compiled when you first load them.
TypeError: ReactIs.isMemo is not a function
    at getStatics (/usr/src/app/.next/server/static/development/pages/_app.js:2457:17)
    at hoistNonReactStatics (/usr/src/app/.next/server/static/development/pages/_app.js:2487:29)
    at hoistNonReactStatics (/usr/src/app/.next/server/static/development/pages/_app.js:2477:17)
    at hoistNonReactStatics (/usr/src/app/.next/server/static/development/pages/_app.js:2477:17)
    at hoistNonReactStatics (/usr/src/app/.next/server/static/development/pages/_app.js:2477:17)
    at NextI18Next._default (/usr/src/app/.next/server/static/development/pages/_app.js:1658:44)
    at Module../pages/_app.tsx (/usr/src/app/.next/server/static/development/pages/_app.js:5539:133)
    at __webpack_require__ (/usr/src/app/.next/server/static/development/pages/_app.js:23:31)
    at Object.0 (/usr/src/app/.next/server/static/development/pages/_app.js:9230:18)
    at __webpack_require__ (/usr/src/app/.next/server/static/development/pages/_app.js:23:31)
    at /usr/src/app/.next/server/static/development/pages/_app.js:91:18
    at Object.<anonymous> (/usr/src/app/.next/server/static/development/pages/_app.js:92:12)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Module.m._compile (/usr/src/app/node_modules/ts-node/src/index.ts:413:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Object.require.extensions.(anonymous function) [as .js] (/usr/src/app/node_modules/ts-node/src/index.ts:416:12)
```

## Occurs in next-i18next version
- `next-i18next@0.33.0`
- `nexjs@8.0.2`
- `typescript@3.3.3333`
- `react@16.8.2`

**Comment by isaachinman** [comment]
What version of React are you on? This is a TypeScript project? Can you please provide a reproducible example?

**Comment by hnq90** [comment]
@isaachinman Yes, it's TypeScript project with React 16.8.2. The error occurred after adding that HOC and refresh the browser.

**Comment by isaachinman** [comment]
https://github.com/zeit/next.js/issues/6117

**Comment by hnq90** [comment]
@isaachinman I read it before but it still works before I added `appWithTranslation`...

**Comment by isaachinman** [comment]
> Can you please provide a reproducible example?

**Comment by mengqing** [comment]
I am also getting this issue after upgraded to the latest version of next-i18next

react@16.8.4
next@8.0.3
next-i18next@0.36.4

**Comment by isaachinman** [comment]
@mengqing https://github.com/zeit/next.js/issues/6117
