### ISSUE TITLE
Problem in simple example

### ISSUE THREAD

**Issue by shakesBeardZ** [isaachinman/next-i18next#230]
I'm having  a problem  running the simple projet. 
what I did 
```
cd examples/simple
```

```
npm i 
```
 
then 
```
npm run dev

> -@1.0.0 dev C:\Users\DaMi\Documents\yahia\new way\next-i18next\examples\simple
> node index.js

module.js:549
    throw err;
    ^

Error: Cannot find module './dist/commonjs/middlewares/next-i18next-middleware'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\DaMi\Documents\yahia\new way\next-i18next\middleware.js:1:80)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! -@1.0.0 dev: `node index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the -@1.0.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\DaMi\AppData\Roaming\npm-cache\_logs\2019-03-13T12_56_28_672Z-debug.log
```

**Comment by isaachinman** [comment]
You need to build the actual source first.

**Comment by isaachinman** [comment]
Instead, do `yarn && yarn run-example` from the root.
