### ISSUE TITLE
AWS Serverless is crashing when accessing endpoint

### ISSUE THREAD

**Issue by Nelrohd** [isaachinman/next-i18next#271]
## Describe the bug
AWS serverless is not working with next-i18next.
The deployment works fine.
The code crash when accessing the endpoints:
```
{
  "message": "Internal server error"
}
```

## Occurs in next-i18next version
Error from CloudWatch logs:
```
module initialization error: Error
at Object.fs.readdirSync (fs.js:904:18)
at getAllNamespaces (/var/task/sls-next-build/index.original.js:14188:17)
at _default (/var/task/sls-next-build/index.original.js:14200:11)
at new NextI18Next (/var/task/sls-next-build/index.original.js:17873:43)
at Object.k7Sn (/var/task/sls-next-build/index.original.js:14249:27)
at __webpack_require__ (/var/task/sls-next-build/index.original.js:23:31)
at Object.YNMu (/var/task/sls-next-build/index.original.js:11315:63)
at __webpack_require__ (/var/task/sls-next-build/index.original.js:23:31)
at Module.OSpu (/var/task/sls-next-build/index.original.js:7612:12)
at __webpack_require__ (/var/task/sls-next-build/index.original.js:23:31)
```

## Steps to reproduce
The code I used: https://github.com/Nelinelo/nextjs-serverless
And:
```
sls deploy
```

## Expected behaviour
It should not crash

**Comment by isaachinman** [comment]
This package is not currently compatible with serverless projects. It relies upon a filesystem being present, and an Express middleware.

**Comment by Nelrohd** [comment]
@isaachinman React-i18n suggest this package for NextJs. Then what package/solution would you suggest?

**Comment by isaachinman** [comment]
Open to any/all sensible contributions to add serverless support. I'm not aware of any direct alternatives to this package at this time.

**Comment by Nelrohd** [comment]
@isaachinman Then shouldn't have a ticket to support serverless to start with?

**Comment by isaachinman** [comment]
Feel free to open one. Please remember that this is an open source project developed in our free time.

**Comment by Nelrohd** [comment]
I understand and I didn't make any complain. My comment was just a suggestion, I apologize if you felt otherwise. Thank you for the great work and support.

**Comment by isaachinman** [comment]
Please do open a ticket and we can look into what it would take.
