### ISSUE TITLE
we use styled-components and next-i18next, it not work

### ISSUE THREAD

**Issue by huanglijiao** [isaachinman/next-i18next#315]
we use styled-components and next-i18next in our project.  
_document.js:

```
import Document, { Head, Main, NextScript } from 'next/document';

import { ServerStyleSheet } from 'styled-components';

export default class MyDocument extends Document {
  static async getInitialProps(ctx) {
    const sheet = new ServerStyleSheet();
    const originalRenderPage = ctx.renderPage;

    try {
      ctx.renderPage = () =>
        originalRenderPage({
          enhanceApp: App => props => sheet.collectStyles(<App {...props} />),
        });

      const initialProps = await Document.getInitialProps(ctx);
      return {
        ...initialProps,
        styles: (
          <>
            {initialProps.styles}
            {sheet.getStyleElement()}
          </>
        ),
      };
    } finally {
      sheet.seal();
    }
  }

  render() {
    return (
      <html>
        <Head>
          <link rel="stylesheet" href="/static/css/normalize.min.css" />
          <link
            rel="shortcut icon"
            href="//cdn-joox.isanook.com/static-inter/favicon.ico"
            type="image/x-icon"
          />
          <meta
            name="viewport"
            content="width=device-width,initial-scale=1,maximum-scale=1,user-scalable=no"
          />
          <meta name="format-detection" content="telephone=no" />
        </Head>
        <body>
          <Main />
          <NextScript />
        </body>
      </html>
    );
  }
}
```

error:

in WithMergedOptions
    in Context.Consumer
    in WithMergedOptions(NamespacesConsumerComponent)
    in LoadNamespace
    in WithMergedOptions
    in Context.Consumer
    in LoadNamespace(NextStaticProvider)
    in Context.Provider
    in I18nextProvider
    in AppWithTranslation
    in withRouter(AppWithTranslation)
    in Context.Provider
    in StyleSheetManager
    in Unknown
    in Context.Provider
    in Context.Provider
    in Context.Provider
    in Context.Provider
{ Invariant Violation: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object.
    at invariant (/Applications/hust-dev/joox-web-nextjs/node_modules/react-dom/cjs/react-dom-server.node.development.js:58:15)
    at ReactDOMServerRenderer.render (/Applications/hust-dev/joox-web-nextjs/node_modules/react-dom/cjs/react-dom-server.node.development.js:3443:7)
    at ReactDOMServerRenderer.read (/Applications/hust-dev/joox-web-nextjs/node_modules/react-dom/cjs/react-dom-server.node.development.js:3161:29)
    at renderToString (/Applications/hust-dev/joox-web-nextjs/node_modules/react-dom/cjs/react-dom-server.node.development.js:3646:27)
    at render (/Applications/hust-dev/joox-web-nextjs/node_modules/next-server/dist/server/render.js:86:16)
    at renderPage (/Applications/hust-dev/joox-web-nextjs/node_modules/next-server/dist/server/render.js:211:20)
    at ctx.renderPage (/Applications/hust-dev/joox-web-nextjs/.next/server/static/development/pages/_document.js:2358:26)
    at Function.value (/Applications/hust-dev/joox-web-nextjs/.next/server/static/development/pages/_document.js:914:41)
    at _callee$ (/Applications/hust-dev/joox-web-nextjs/.next/server/static/development/pages/_document.js:2368:77)
    at tryCatch (/Applications/hust-dev/joox-web-nextjs/node_modules/regenerator-runtime/runtime.js:62:40)
    at Generator.invoke [as _invoke] (/Applications/hust-dev/joox-web-nextjs/node_modules/regenerator-runtime/runtime.js:288:22)
    at Generator.prototype.(anonymous function) [as next] (/Applications/hust-dev/joox-web-nextjs/node_modules/regenerator-runtime/runtime.js:114:21)
    at asyncGeneratorStep (/Applications/hust-dev/joox-web-nextjs/.next/server/static/development/pages/index.js:474:24)
    at _next (/Applications/hust-dev/joox-web-nextjs/.next/server/static/development/pages/index.js:496:9)
    at /Applications/hust-dev/joox-web-nextjs/.next/server/static/development/pages/index.js:503:7
    at new Promise (<anonymous>) name: 'Invariant Violation', framesToPop: 1 }

So the styled-components and next-i18next can not be used in one project?

**Comment by isaachinman** [comment]
1. Format your comments properly
2. Provide enough context that someone might be able to actually give insight on the problem you are facing

**Comment by huanglijiao** [comment]
We use nextjs and next-i18next in our project. Then we want to use styled-components. We follow the steps in the example [https://github.com/zeit/next.js/tree/canary/examples/with-styled-components], but it not work, the error is showed above.

**Comment by kachkaev** [comment]
@huanglijiao feel free to check out my mini-project that uses both next-i18next and styled-components: https://gitlab.com/kachkaev/website-frontend/. Hope it helps you find the issue in your code that's causing the error.

**Comment by huanglijiao** [comment]
thank， I solved it！

**Comment by kachkaev** [comment]
@huanglijiao feel free to share the details of what was wrong to help others solve similar problems.

**Comment by hectordommo** [comment]
@huanglijiao could you share what did you found out ? thanks

**Comment by rebeccawirkn** [comment]
I had the same problem. I fixed it by adding a _.babelrc_ file with these parameters in the root of my project:
```
{
    "presets": ["next/babel"],
    "plugins": [["styled-components", {"ssr":true}]]
}
```
