### ISSUE TITLE
In incidental builds I get "Cannot read property 'wait' of null"

### ISSUE THREAD

**Issue by StarpTech** [isaachinman/next-i18next#335]
## Describe the bug
Hello, in random builds I get the error

```
test: react-i18next:: You will need pass in an i18next instance either by props, using I18nextProvider or by using i18nextReactModule. Learn more https://react.i18next.com/components/overview#getting-the-i-18-n-function-into-the-flow
test: TypeError: Cannot read property 'wait' of null
test:     at NamespacesConsumerComponent.render (/home/deus/Repositories/test/packages/test/.next/server/static/development/pages/index.js:3879:33)
test:     at c (/home/deus/Repositories/test/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:35:231)
test:     at Sa (/home/deus/Repositories/test/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:36:1)
test:     at a.render (/home/deus/Repositories/test/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:41:467)
test:     at a.read (/home/deus/Repositories/test/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:41:58)
test:     at renderToString (/home/deus/Repositories/test/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:53:83)
test:     at render (/home/deus/Repositories/test/node_modules/next-server/dist/server/render.js:86:16)
test:     at renderPage (/home/deus/Repositories/test/node_modules/next-server/dist/server/render.js:211:20)
test:     at Function.value (/home/deus/Repositories/test/packages/test/.next/server/static/zc6vAW9XvmLM2kKQPrTcg/pages/_document.js:607:41)
test:     at _callee$ (/home/deus/Repositories/test/packages/test/.next/server/static/zc6vAW9XvmLM2kKQPrTcg/pages/_document.js:1985:78)
test: [TypeError: Cannot read property 'wait' of null]
```
then after another rebuild it works again. I already delete the dist folder before building. Any idea?

## Occurs in next-i18next version
next-i18next: 0.40.1
next.js: 8.1.0

## Config

```
  defaultLanguage: 'en',
  localePath: 'static/locales',
  fallbackLng: 'en',
  otherLanguages: ['de', 'en'],
  detection: {
    lookupCookie: 'lang',
    order: ['querystring', 'cookie', 'header'],
    caches: ['cookie']
  },
```

## Steps to reproduce
I can't reproduce it.

**Comment by isaachinman** [comment]
Not sure why you've got `en` as both your default language and in `otherLanguages`. Besides that, without steps to reproduce, no one will be able to assist.

**Comment by StarpTech** [comment]
I opened it just in case whether somebody already faced with that issue.

**Comment by isaachinman** [comment]
This in general is the same error you will receive whenever there isn't a `I18nextProvider` or valid i18next context in your React tree - there are many cases where it can occur. Let's leave the issue open though and see if anyone else feels they are experiencing the same thing.

**Comment by StarpTech** [comment]
The interesting question is why it can't be reproduced every time? It feels like race condition.

**Comment by isaachinman** [comment]
Yes indeed - sounds like a race condition. Could you perhaps provide a repo where I can observe this occurring?

**Comment by StarpTech** [comment]
Yes, I will try.

**Comment by StarpTech** [comment]
I couldn't reproduce it since weeks.
