### ISSUE TITLE
Error on yarn dev

### ISSUE THREAD

**Issue by NikolayPetyukh** [isaachinman/next-i18next#446]
## Describe the bug
```
root@cs635985:~/next-i18next/examples/simple# yarn dev
yarn run v1.17.3
$ node index.js
internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module './dist/commonjs/middlewares/next-i18next-middleware'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/root/next-i18next/middleware.js:1:18)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

## Occurs in next-i18next version
```
commit 0c714399370eb83192cf08403ccf86f567aac4a2 (HEAD -> master, tag: v0.54.0, origin/master, origin/HEAD)
```

## Steps to reproduce
```
git clone https://github.com/isaachinman/next-i18next.git
cd next-i18next/examples/simple/
yarn install
yarn dev
```

## Expected behaviour
Application starts

## Screenshots
![image](https://user-images.githubusercontent.com/8134986/62865170-669ce800-bd16-11e9-9159-308d86c885a8.png)

## OS (please complete the following information)
 - Device: VPS, Ubuntu 18.04. Same error on Windows 10 hardware PC
 - Browser: not applicable, application didn't start

**Comment by huongdevvn** [comment]
Go to root folder `next-i18next` and run command `yarn run-example`.

**Comment by isaachinman** [comment]
Did you take a look at the scripts in `package.json` in the root?

**Comment by NikolayPetyukh** [comment]
> 
> 
> Did you take a look at the scripts in `package.json` in the root?

Sorry, i am noob.
