### ISSUE TITLE
Example simple doesnt work

### ISSUE THREAD

**Issue by StarpTech** [isaachinman/next-i18next#448]
As titled. Try to run https://github.com/isaachinman/next-i18next/tree/master/examples/simple I got this error client side.
```
main-07bacf96f69fc1253a52.js:1 r.isMemo is not a function
TypeError: r.isMemo is not a function
    at l (http://localhost:3000/_next/static/chunks/commons.e03c7ac8a6e2f972518d.js:1:205976)
    at e (http://localhost:3000/_next/static/chunks/commons.e03c7ac8a6e2f972518d.js:1:206385)
    at e (http://localhost:3000/_next/static/chunks/commons.e03c7ac8a6e2f972518d.js:1:206333)
    at e (http://localhost:3000/_next/static/chunks/commons.e03c7ac8a6e2f972518d.js:1:206333)
    at e (http://localhost:3000/_next/static/chunks/commons.e03c7ac8a6e2f972518d.js:1:206333)
    at e.t.default (http://localhost:3000/_next/static/chunks/commons.e03c7ac8a6e2f972518d.js:1:198943)
    at Module.295 (http://localhost:3000/_next/static/o8Mn5I9VyckaafLHW9nZV/pages/_app.js:1:579)
    at l (http://localhost:3000/_next/static/runtime/webpack-3df6523e264ff2ac6548.js:1:520)
    at http://localhost:3000/_next/static/o8Mn5I9VyckaafLHW9nZV/pages/_app.js:1:2480
    at http://localhost:3000/_next/static/runtime/main-07bacf96f69fc1253a52.js:1:12721
```

Error message in development mode:
```
index.js:1 Error was not caught TypeError: ReactIs.isMemo is not a function
    at getStatics (hoist-non-react-statics.cjs.js:53)
    at hoistNonReactStatics (hoist-non-react-statics.cjs.js:83)
    at hoistNonReactStatics (hoist-non-react-statics.cjs.js:73)
    at hoistNonReactStatics (hoist-non-react-statics.cjs.js:73)
    at hoistNonReactStatics (hoist-non-react-statics.cjs.js:73)
    at NextI18Next._default (app-with-translation.js:245)
    at Module../pages/_app.js (_app.js:12)
    at __webpack_require__ (bootstrap:792)
    at fn (bootstrap:150)
    at next-client-pages-loader.js:3
```

**Comment by StarpTech** [comment]
I could fix it by reinstall everything really strange but the example is still invalid for the latest version e.g node.js doesn't support default export. We need to use `require(..).default`.

**Comment by isaachinman** [comment]
The simple example is both run in e2e tests during CI and also currently online via Heroku. You'll need to be more specific.

**Comment by StarpTech** [comment]
My mistake I didn't test against the latest state with the latest version.
