### ISSUE TITLE
pkg support

### ISSUE THREAD

**Issue by SkunSHD** [isaachinman/next-i18next#507]
I'm using [this](https://medium.com/@isaachinman/creating-localised-nextjs-apps-with-next-i18next-f01d5e610307) standard next-i18next setup and deploy it with pkg and docker [like this](https://medium.com/@evenchange4/deploy-a-commercial-next-js-application-with-pkg-and-docker-5c73d4af2ee)

The docker image creates ok but it fails when I run it:

```
docker run --rm -it -p 3003:3003 -e "PORT=3003" -e "API_URL=https://API_URL.com" app
pkg/prelude/bootstrap.js:1185
throw error;
^
Error: ENOENT: no such file or directory, scandir '/app/static/locales/en'

If you want to compile the package/file into executable, please pay attention to compilation warnings and specify a literal in 'require' call. 2) If you don't want to compile the package/file into executable and want to 'require' it from filesystem (likely plugin), specify an absolute path in 'require' call using process.cwd() or process.execPath.
at Object.readdirSync (fs.js:785:3)
at Object.fs.readdirSync (pkg/prelude/bootstrap.js:787:35)
at getAllNamespaces (/snapshot/app/node_modules/next-i18next/dist/commonjs/config/create-config.js:49:19)
at _default (/snapshot/app/node_modules/next-i18next/dist/commonjs/config/create-config.js:54:27)
at new NextI18Next (/snapshot/app/node_modules/next-i18next/dist/commonjs/index.js:30:43)
at Object. (/snapshot/app/src/i18n.js:0:0)
at Module._compile (pkg/prelude/bootstrap.js:1261:22)
at Object.Module._extensions..js (internal/modules/cjs/loader.js:710:10)
at Module.load (internal/modules/cjs/loader.js:598:32)
at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
```
It fails in this line:
`combinedConfig.ns = getAllNamespaces(path.join(process.cwd(), "".concat(localePath, "/").concat(defaultLanguage)));`

As I understood it's because static folder is packed in binary file. I didn't find a way how to solve or feature for that.

**Comment by isaachinman** [comment]
You will need to debug your own unique filesystem requirements, or provide locales via a non-filesystem approach.
