### ISSUE TITLE
Missing dependency @babel/runtime

### ISSUE THREAD

**Issue by florian-milky** [isaachinman/next-i18next#746]
## Describe the bug

Causes an issue at runtime when using npm `--production` option

## Occurs in next-i18next version
latest version

## Steps to reproduce

Build project using next-i18next with `npm i --production`
Have custom server setup
Start your server

```
internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module 'regenerator-runtime/runtime'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (<redacted>/node_modules/next-i18next/dist/commonjs/hocs/app-with-translation.js:32:1)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
```

## Expected behaviour
Should not cause error

**Comment by florian-milky** [comment]
Apologies this was an issue with npm transitive dependencies so regenerator-runtime was not hoisted at the root folder.
`npm dedupe` solved my issue
