### ISSUE TITLE
TypeError [ERR_INVALID_ARG_TYPE] when using getServerSideProps

### ISSUE THREAD

**Issue by avaforvr** [isaachinman/next-i18next#763]
## Describe the bug
When using both i18n Link component and getServerSideProps，Error show in cmd
```
TypeError [ERR_INVALID_ARG_TYPE]: The "string" argument must be of type string or an instance of Buffer or ArrayBuffer. Received undefined
    at Function.byteLength (buffer.js:723:11)
    at sendPayload (D:\workspace\themis_next\node_modules\next\dist\next-server\server\send-payload.js:11:44)
    at Server.renderToHTMLWithComponents (D:\workspace\themis_next\node_modules\next\dist\next-server\server\next-server.js:632:42)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Server.renderErrorToHTML (D:\workspace\themis_next\node_modules\next\dist\next-server\server\next-server.js:706:24)
    at async Server.renderToHTML (D:\workspace\themis_next\node_modules\next\dist\next-server\server\next-server.js:677:16)
    at async Server.render (D:\workspace\themis_next\node_modules\next\dist\next-server\server\next-server.js:486:22)
    at async Object.fn (D:\workspace\themis_next\node_modules\next\dist\next-server\server\next-server.js:257:17)
    at async Router.execute (D:\workspace\themis_next\node_modules\next\dist\next-server\server\router.js:28:28)
    at async Server.run (D:\workspace\themis_next\node_modules\next\dist\next-server\server\next-server.js:453:29) {
  code: 'ERR_INVALID_ARG_TYPE'
}
```
`import NextLink from 'next/link'` works fine.

## Occurs in next-i18next version
v4.5.0

## Steps to reproduce
https://github.com/avaforvr/nextjs-i18n

Initialize the project and add nextjs-i18next as doc.

## Expected behaviour
I expect it to work fine or get some help to fix the bug.

## Screenshots
![image](https://user-images.githubusercontent.com/5516208/88166055-3f9aa600-cc49-11ea-85df-5b9506dfd923.png)

## OS (please complete the following information)
 - Device: Windows 10, macOS Catalina 10.15.3
 - Browser: Chrome 80.0.3987.149
 - Node: v12.16.2
 - Next.js: 9.4.4

## Additional context
None

**Comment by isaachinman** [comment]
Interesting, this does indeed seem to somehow be related to `getServerSideProps`, as this doesn't throw without use of `getServerSideProps`.

The relevant code is of course the [wrapping of `Link` within `next-i18next`, here](https://github.com/isaachinman/next-i18next/blob/master/src/components/Link.tsx).

Given the fact that your example has locale subpaths, the output for:

```jsx
<Link href="/another"><a>i18nLink: Go Another</a></Link>
```

Ends up looking like:

```jsx
correctedAs: '/en/another',
correctedHref: Url {
  protocol: null,
  slashes: null,
  auth: null,
  host: null,
  port: null,
  hostname: null,
  hash: null,
  query: [Object: null prototype] { lng: 'en', subpath: 'en' },
  pathname: '/another',
  path: '/another',
  href: '/another'
}
```

And this somehow throws the error from `next-server/server/send-payload.js:2:129`.

However, if I simply hardcode the values to:

```jsx
correctedAs: '/en/another',
correctedHref: '/[subpath]/another'
```

The issue goes away. @capellini or @timer, any thoughts on why this might occur? The [link docs](https://nextjs.org/docs/api-reference/next/link) aren't explicit about how to use a URL object `href` with an `as` value as well, and certainly don't mention anything about `getServerSideProps`. Is this an error on the `next-i18next` side, or a bug within the NextJs core?

**Comment by Timer** [comment]
This is fixed on `next@canary`.

**Comment by avaforvr** [comment]
@isaachinman @Timer  `next@canary` works fine.  You ' re so helpful . thanks a lot.
