### ISSUE TITLE
withTranslation with decorator (typescript error)

### ISSUE THREAD

**Issue by ktjd123** [isaachinman/next-i18next#767]
## Describe the bug
withTranslation with decorator (typescript error)

## Occurs in next-i18next version
"next-i18next": "^4.5.0",

## Steps to reproduce
use typescript, withTranslation() decorator

## Expected behaviour
no error

## Screenshots
![스크린샷 2020-07-25 오후 4 44 00](https://user-images.githubusercontent.com/15044488/88451986-0f941280-ce96-11ea-9d94-f1127d778899.png)

## OS (please complete the following information)
 - Device: macOS
 - Browser: chrome

**Comment by ktjd123** [comment]
when try to build with @ts-ignore this happens.

```ts
 ✘  ~/S/artgravia   master ±  yarn build
yarn run v1.22.4
$ rm -rf .next && rm -rf build && tsc -p tsconfig.server.json && next build && mv .next build/.next && cp package.json build && cp pm2.json ./build && cp -r public build/public
Warning: Built-in CSS support is being disabled due to custom CSS configuration being detected.
See here for more info: https://err.sh/next.js/built-in-css-disabled

> Using external babel configuration
> Location: "/Users/peter/Server/artgravia/.babelrc"
Creating an optimized production build  

Compiled successfully.

Warning: You have opted-out of Automatic Static Optimization due to `getInitialProps` in `pages/_app`. This does not opt-out pages with `getStaticProps`
Read more: https://err.sh/next.js/opt-out-auto-static-optimization


> Build error occurred
ReferenceError: withTranslation is not defined
    at Object.m/eG (/Users/peter/Server/artgravia/.next/server/static/ibhHznMyLzVkrZgRGgMm8/pages/admin/photo.js:3090:18)
    at __webpack_require__ (/Users/peter/Server/artgravia/.next/server/static/ibhHznMyLzVkrZgRGgMm8/pages/admin/photo.js:29:31)
    at Module.p9MV (/Users/peter/Server/artgravia/.next/server/static/ibhHznMyLzVkrZgRGgMm8/pages/admin/photo.js:20377:69)
    at __webpack_require__ (/Users/peter/Server/artgravia/.next/server/static/ibhHznMyLzVkrZgRGgMm8/pages/admin/photo.js:29:31)
    at Object.8 (/Users/peter/Server/artgravia/.next/server/static/ibhHznMyLzVkrZgRGgMm8/pages/admin/photo.js:403:18)
    at __webpack_require__ (/Users/peter/Server/artgravia/.next/server/static/ibhHznMyLzVkrZgRGgMm8/pages/admin/photo.js:29:31)
    at /Users/peter/Server/artgravia/.next/server/static/ibhHznMyLzVkrZgRGgMm8/pages/admin/photo.js:104:18
    at Object.<anonymous> (/Users/peter/Server/artgravia/.next/server/static/ibhHznMyLzVkrZgRGgMm8/pages/admin/photo.js:107:10)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10) {
  type: 'ReferenceError'
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
 ✘  ~/S/artgravia   master ±  
```

**Comment by isaachinman** [comment]
Please provide a full repository.

**Comment by ktjd123** [comment]
https://github.com/ktjd123/next-18next-ts-example

@isaachinman 

you can check with this repo Thank you.

yarn d to start dev mode
yarn build to build

**Comment by isaachinman** [comment]
@ktjd123 What are you seeing is a generic pattern where HOC props can be tricky to type in TS. As far as I can see, there's nothing specific here to `next-i18next`. Have a search through StackOverflow on how to type HOCs in React/TS. Good luck!

**Comment by ktjd123** [comment]
@isaachinman  Thank you for your help. Thanks!
