### ISSUE TITLE
"Error occurred prerendering page" when using localeSubpaths and next export

### ISSUE THREAD

**Issue by lud-hu** [isaachinman/next-i18next#812]
## Describe the bug
I can't get LocalSubpaths to work with **next export**. I followed the instructions in the documentation, but I get this error for multiple pages ("/", "/404", "/404.html", "/second-page"):
```
Error occurred prerendering page "/second-page". Read more: https://err.sh/next.js/prerender-error
TypeError: res.writeHead is not a function
    at redirectWithoutCache (.../repos/next-i18next/examples/simple/node_modules/next-i18next/dist/commonjs/utils/redirect-without-cache.js:12:7)
    at .../repos/next-i18next/examples/simple/node_modules/next-i18next/dist/commonjs/middlewares/next-i18next-middleware.js:81:48
    at .../repos/next-i18next/examples/simple/node_modules/next-i18next/dist/commonjs/hocs/app-with-translation.js:249:38
    at new Promise (<anonymous>)
    at _loop$ (.../repos/next-i18next/examples/simple/node_modules/next-i18next/dist/commonjs/hocs/app-with-translation.js:248:36)
    at tryCatch (.../repos/next-i18next/examples/simple/node_modules/regenerator-runtime/runtime.js:63:40)
    at Generator.invoke [as _invoke] (.../repos/next-i18next/examples/simple/node_modules/regenerator-runtime/runtime.js:293:22)
    at Generator.next (.../repos/next-i18next/examples/simple/node_modules/regenerator-runtime/runtime.js:118:21)
    at tryCatch (.../repos/next-i18next/examples/simple/node_modules/regenerator-runtime/runtime.js:63:40)
    at maybeInvokeDelegate (.../repos/next-i18next/examples/simple/node_modules/regenerator-runtime/runtime.js:356:18)
```
## Occurs in next-i18next version
next-18next version 6.0.2

## Steps to reproduce
1. Clone example/simple repo.
2. Add localeSubpaths as described in [documentation](https://github.com/isaachinman/next-i18next#5-locale-subpaths) to i18n.js

```js
module.exports = new NextI18Next({
  otherLanguages: ['de'],
  localeSubpaths: {
    de: 'de',
    en: 'en'
  },
  localePath: path.resolve('./public/static/locales')
})
```
and to next.config.js
```js
const localeSubpaths = {
  de: 'de',
  en: 'en'
}
```
3. Execute **next build** and **next export**

## Expected behaviour
Locale subpaths reachable in e.g. /en or /de when using **next export**.

## OS (please complete the following information)
 - Device: MBP 2014 15"
 - Browser: Chrome 83.0.4103.106

**Comment by isaachinman** [comment]
This package does not support `next export` as we still have server side logic. You'll notice this is noted in [the docs](https://docs.lokalise.com/en/articles/1592525-livejs-web-in-context-editor).

**Comment by lud-hu** [comment]
You're right, its well hidden in the last lines (even though your link is wrong).
Thanks for the quick answer!

**Comment by Vivek205** [comment]
Is this issue fixed?
I'm facing the same issue.
