### ISSUE TITLE
TypeError: Cannot destructure property 'Component' of 'undefined' as it is undefined.

### ISSUE THREAD

**Issue by RyanPayso13** [isaachinman/next-i18next#836]
## Describe the bug
When I try to start the dev server with `yarn dev` the following error is thrown in the terminal when I navigate to the home page.

`TypeError: Cannot destructure property 'Component' of 'undefined' as it is undefined.`

## Occurs in next-i18next version
9.5.3

## Steps to reproduce
https://github.com/RyanPayso13/tmapp

## Expected behaviour
The dev server should not throw any Type errors in the console and I should be able to view the home page rather than .

## Stacktrace
```
event - build page: /
wait  - compiling...
event - compiled successfully
TypeError: Cannot destructure property 'Component' of 'undefined' as it is undefined.
    at Function.appGetInitialProps (webpack-internal:///./node_modules/next/dist/pages/_app.js:22:3)
    at Function.TextMiningApp.getInitialProps (webpack-internal:///./src/pages/_app.tsx:49:79)
    at _callee2$ (/Users/ryanpays/workspace/tmapp/node_modules/next-i18next/dist/commonjs/hocs/app-with-translation.js:320:43)
    at tryCatch (/Users/ryanpays/workspace/tmapp/node_modules/regenerator-runtime/runtime.js:63:40)
    at Generator.invoke [as _invoke] (/Users/ryanpays/workspace/tmapp/node_modules/regenerator-runtime/runtime.js:293:22)
    at Generator.next (/Users/ryanpays/workspace/tmapp/node_modules/regenerator-runtime/runtime.js:118:21)
    at asyncGeneratorStep (/Users/ryanpays/workspace/tmapp/node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:24)
    at _next (/Users/ryanpays/workspace/tmapp/node_modules/@babel/runtime/helpers/asyncToGenerator.js:25:9)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
TypeError: Cannot destructure property 'Component' of 'undefined' as it is undefined.
    at Function.appGetInitialProps (webpack-internal:///./node_modules/next/dist/pages/_app.js:22:3)
    at Function.TextMiningApp.getInitialProps (webpack-internal:///./src/pages/_app.tsx:49:79)
    at _callee2$ (/Users/ryanpays/workspace/tmapp/node_modules/next-i18next/dist/commonjs/hocs/app-with-translation.js:320:43)
    at tryCatch (/Users/ryanpays/workspace/tmapp/node_modules/regenerator-runtime/runtime.js:63:40)
    at Generator.invoke [as _invoke] (/Users/ryanpays/workspace/tmapp/node_modules/regenerator-runtime/runtime.js:293:22)
    at Generator.next (/Users/ryanpays/workspace/tmapp/node_modules/regenerator-runtime/runtime.js:118:21)
    at asyncGeneratorStep (/Users/ryanpays/workspace/tmapp/node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:24)
    at _next (/Users/ryanpays/workspace/tmapp/node_modules/@babel/runtime/helpers/asyncToGenerator.js:25:9)
TypeError: Cannot destructure property 'Component' of 'undefined' as it is undefined.
    at Function.appGetInitialProps (webpack-internal:///./node_modules/next/dist/pages/_app.js:22:3)
    at Function.TextMiningApp.getInitialProps (webpack-internal:///./src/pages/_app.tsx:49:79)
    at _callee2$ (/Users/ryanpays/workspace/tmapp/node_modules/next-i18next/dist/commonjs/hocs/app-with-translation.js:320:43)
    at tryCatch (/Users/ryanpays/workspace/tmapp/node_modules/regenerator-runtime/runtime.js:63:40)
    at Generator.invoke [as _invoke] (/Users/ryanpays/workspace/tmapp/node_modules/regenerator-runtime/runtime.js:293:22)
    at Generator.next (/Users/ryanpays/workspace/tmapp/node_modules/regenerator-runtime/runtime.js:118:21)
    at asyncGeneratorStep (/Users/ryanpays/workspace/tmapp/node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:24)
    at _next (/Users/ryanpays/workspace/tmapp/node_modules/@babel/runtime/helpers/asyncToGenerator.js:25:9)
```
## Screenshot
![Screenshot 2020-09-23 at 19 25 56](https://user-images.githubusercontent.com/25579374/94053893-cd724900-fdd2-11ea-8062-10837cd8ff3e.png)

## OS (please complete the following information)
 - Device: MBP 2017

**Comment by isaachinman** [comment]
Please provide a more comprehensive bug report, and stack trace.

**Comment by RyanPayso13** [comment]
I found the issue.

I was destructuring of `appContext` in `_app.tsx`.

When I remove it runs fine.

```
MyApp.getInitialProps = async (appContext: AppContext) => ({
  ...(await App.getInitialProps(appContext)),
});
```
