### ISSUE TITLE
How to mock the `Link` and `Router` form testing next-i18next ?

### ISSUE THREAD

**Issue by ashish328** [isaachinman/next-i18next#846]
## Describe the bug
setup of next-i18next -  i18n.ts
```const NextI18Next = require('next-i18next').default
const { localeSubpaths } = require('next/config').default().publicRuntimeConfig
const path = require('path')

const NextI18NextInstance = new NextI18Next({
  defaultLanguage: 'en',
  browserLanguageDetection: true,
  otherLanguages: ['en', 'ar'],
  localeSubpaths,
  localePath: path.resolve('./public/static/locales')
})

export default NextI18NextInstance

export const {appWithTranslation, Link, Trans, Router, config, withTranslation, i18n} = NextI18NextInstance
``` 
Setup of react-i18next for tests  in __mock__/i18n.ts
```import i18n from 'i18next';
import { initReactI18next } from 'react-i18next';

i18n
  .use(initReactI18next)
  .init({
    lng: 'en',
    fallbackLng: 'en',

    // have a common namespace used around the full app
    ns: ['common', 'signIn'],
    defaultNS: 'common',

    debug: false,

    interpolation: {
      escapeValue: false, // not needed for react!!
    },

    resources: { en: { translations: {} } },
  });
export default i18n;
```
my component where i used `Link` i18n.ts
```import React, { FC, useState, useEffect } from 'react'
import { Link, Router } from 'i18n'

const SignIn: FC = props => {
...
return (
    <>
      <Link href="/auth/reset-password">
          <Typography className={classes.forgotPassword} variant="body2" color="primary">
                {t('signIn:forgotPassword')}
          </Typography>
      </Link>
   </>
)
```
when i run  test it shows me an error.
```__tests__/components/SignIn.test.tsx
  ● Test suite failed to run

    You are passing an undefined module! Please check the object you are passing to i18next.use()

       5 | 
       6 | i18n
    >  7 |   .use(initReactI18next)
         |    ^
       8 |   .init({
       9 |     lng: 'en',
      10 |     fallbackLng: 'en',

      at I18n.use (node_modules/i18next/dist/cjs/i18next.js:1996:26)
      at Object.<anonymous> (__mocks__/i18n.tsx:7:4)
      at Object.<anonymous> (components/sign-in-flow/SignIn.tsx:20:1)
      at Object.<anonymous> (__tests__/components/SignIn.test.tsx:3:1)
```
the error is because i have mocked the react-i18next and react-i18next doesn't have `Link` component. i need a way to mock the `Link`  from next-i18next to run the test with out any errors.

**Comment by isaachinman** [comment]
Please post on StackOverflow for general help questions. Good luck!

**Comment by ashish328** [comment]
@isaachinman as you suggest posted it on stackOverflow  https://stackoverflow.com/questions/64268912/how-to-set-up-test-environment-next-js-project-using-next-18next-when-link-of.
if have made few changes in mocking react-i18next, now am getting a new error 
```
    TypeError: (0 , _reactI18next.withTranslation) is not a function

    > 1 | const NextI18Next = require('next-i18next').default
        |                     ^
      2 | const { localeSubpaths } = require('next/config').default().publicRuntimeConfig
      3 | const path = require('path')
      4 | 

      at Object.<anonymous> (node_modules/next-i18next/dist/commonjs/components/Link.js:132:50)
      at Object.<anonymous> (node_modules/next-i18next/dist/commonjs/components/index.js:21:36)
      at Object.<anonymous> (node_modules/next-i18next/dist/commonjs/hocs/app-with-translation.js:86:19)
      at Object.<anonymous> (node_modules/next-i18next/dist/commonjs/hocs/index.js:19:27)
      at Object.<anonymous> (node_modules/next-i18next/dist/commonjs/index.js:36:13)
      at Object.<anonymous> (i18n.ts:1:21)
      at Object.<anonymous> (components/sign-in-flow/SignIn.tsx:16:1)
      at Object.<anonymous> (__tests__/components/SignIn.test.tsx:3:1)
```
