### ISSUE TITLE
Locale in the format ['en-US ', ' en-UK '] does not work.

### ISSUE THREAD

**Issue by raff444** [isaachinman/next-i18next#941]
Hello, I'm using 'nextI18next', and the package works perfectly when using locale in the format ['en', 'es', 'pt']. However, when using in the format ['en-US ',' en-UK ',' pt-PT ',' pt-BR '], the i18next does not work and generates an internal error.

I've read the documentation, put other options, but it doesn't work.

I created a folder with the name of the language inside locales, in the 'en-US' format it didn't work, but only in the 'en' format.

I need to create a translation of the same language, for different countries, because there are different words in each country.

```
** i18n.js **

const NextI18Next = require('next-i18next').default
const { localeSubpaths } = require('next/config').default().publicRuntimeConfig
const path = require('path')

module.exports = new NextI18Next({
 
  defaultNS: 'common',

  localeSubpaths: {
      pt-PT: "pt-pt",
      en-US: 'en-us',
      en-UK: 'en-uk'
  }, 

  otherLanguages: ['pt-PT', 'en-US', 'en-UK'],  

  load: 'all',

  fallbackLng: 'en-US',
 
  localePath: path.resolve('./public/static/locales'), 

  browserLanguageDetection: true,

  shallowRender: true

})
```

 #### How do you solve this problem?

**Comment by j4nos** [comment]
Same problem here. Did you figure out solution?

**Comment by isaachinman** [comment]
> generates an internal error

What is the error?

**Comment by raff444** [comment]
**Failed to load resource: the server responded with a status of 500 (Internal Server Error)**

This error only happens when I use it in the "en-US" format, it seems that I can't find the path of the 'locales' folder with the language namespace "en-US".

However when I use it in the 'en' format, there is no error in the 'resource' and 'namespaces', it works normally with 'en'.

What is the correct way to create a folder inside the locales for "en-US"?

#### I already created the folder for 'en-US' in the following ways, and they all gave an error:
```
./public/static/locales/en-us
./public/static/locales/en-US
./public/static/locales/enUS
./public/static/locales/enus
```

#### Only works in 'en' format:
`. /public/ static/locales/en
`
### How to solve this?

**Comment by isaachinman** [comment]
Can you please post the actual stacktrace for the 500?

**Comment by raff444** [comment]
**the next-i18next package is generating this automatic path 'public/static/locales/en'. Which is different from my 'en-US' configuration.**

```
error - Error: Default namespace not found at /home/devops/Developer/Code/Model/NextJS/i18n-traducao-idioma-site/i18n/public/static/locales/en/common.json
    at createConfig (/home/devops/Developer/Code/Model/NextJS/i18n-traducao-idioma-site/i18n/node_modules/next-i18next/dist/commonjs/config/create-config.js:117:19)
    at new NextI18Next (/home/devops/Developer/Code/Model/NextJS/i18n-traducao-idioma-site/i18n/node_modules/next-i18next/dist/commonjs/index.js:57:48)
    at eval (webpack-internal:///./i18n.js:9:18)
    at Object../i18n.js (/home/devops/Developer/Code/Model/NextJS/i18n-traducao-idioma-site/i18n/.next/server/pages/_app.js:114:1)
    at __webpack_require__ (/home/devops/Developer/Code/Model/NextJS/i18n-traducao-idioma-site/i18n/.next/server/pages/_app.js:23:31)
    at eval (webpack-internal:///./src/pages/_app.js:8:63)
    at Module../src/pages/_app.js (/home/devops/Developer/Code/Model/NextJS/i18n-traducao-idioma-site/i18n/.next/server/pages/_app.js:160:1)
    at __webpack_require__ (/home/devops/Developer/Code/Model/NextJS/i18n-traducao-idioma-site/i18n/.next/server/pages/_app.js:23:31)
    at Object.0 (/home/devops/Developer/Code/Model/NextJS/i18n-traducao-idioma-site/i18n/.next/server/pages/_app.js:182:18)
    at __webpack_require__ (/home/devops/Developer/Code/Model/NextJS/i18n-traducao-idioma-site/i18n/.next/server/pages/_app.js:23:31)
    at /home/devops/Developer/Code/Model/NextJS/i18n-traducao-idioma-site/i18n/.next/server/pages/_app.js:91:18
    at Object.<anonymous> (/home/devops/Developer/Code/Model/NextJS/i18n-traducao-idioma-site/i18n/.next/server/pages/_app.js:94:10)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
Error: Default namespace not found at /home/devops/Developer/Code/Model/NextJS/i18n-traducao-idioma-site/i18n/public/static/locales/en/common.json
    at createConfig (/home/devops/Developer/Code/Model/NextJS/i18n-traducao-idioma-site/i18n/node_modules/next-i18next/dist/commonjs/config/create-config.js:117:19)
    at new NextI18Next (/home/devops/Developer/Code/Model/NextJS/i18n-traducao-idioma-site/i18n/node_modules/next-i18next/dist/commonjs/index.js:57:48)
    at eval (webpack-internal:///./i18n.js:9:18)
    at Object../i18n.js (/home/devops/Developer/Code/Model/NextJS/i18n-traducao-idioma-site/i18n/.next/server/pages/_app.js:114:1)
    at __webpack_require__ (/home/devops/Developer/Code/Model/NextJS/i18n-traducao-idioma-site/i18n/.next/server/pages/_app.js:23:31)
    at eval (webpack-internal:///./src/pages/_app.js:8:63)
    at Module../src/pages/_app.js (/home/devops/Developer/Code/Model/NextJS/i18n-traducao-idioma-site/i18n/.next/server/pages/_app.js:160:1)
    at __webpack_require__ (/home/devops/Developer/Code/Model/NextJS/i18n-traducao-idioma-site/i18n/.next/server/pages/_app.js:23:31)
    at Object.0 (/home/devops/Developer/Code/Model/NextJS/i18n-traducao-idioma-site/i18n/.next/server/pages/_app.js:182:18)
    at __webpack_require__ (/home/devops/Developer/Code/Model/NextJS/i18n-traducao-idioma-site/i18n/.next/server/pages/_app.js:23:31)
    at /home/devops/Developer/Code/Model/NextJS/i18n-traducao-idioma-site/i18n/.next/server/pages/_app.js:91:18
    at Object.<anonymous> (/home/devops/Developer/Code/Model/NextJS/i18n-traducao-idioma-site/i18n/.next/server/pages/_app.js:94:10)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)

```

**Comment by raff444** [comment]
**I found the problem, the 'defaultLanguage' option was disabled. Thanks for your attention.**

**Comment by raff444** [comment]
could you give me a hint, of any package for nextjs, for when to select the language and country, set the direction of the page text (left or right), time format, currency, alphabet, etc.

**Comment by isaachinman** [comment]
@raff444 Glad you could figure it out. Not sure exactly what you're asking, but it sounds like exactly what [i18next](https://www.i18next.com/) does. Good luck!
